version: '3.7'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  # Loki listens on this port
    volumes:
      - /home/devops/grafana/Govy_promGraf/PromGraf/loki-config.yaml:/etc/loki/local-config.yaml  # Mount Loki's config file
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /home/devops/grafana/Govy_promGraf/PromGraf/promtail-config.yaml:/etc/promtail/promtail-config.yaml  # Mount Promtail's config file
      - /var/log:/var/log  # Mount the host's log directory
    command: -config.file=/etc/promtail/promtail-config.yaml
